### ISSUE TITLE
Update assets

### ISSUE THREAD

**Issue by canihavesomecoffee** [CCExtractor/sample-platform#108]
Some of the platform libraries we are using are somewhat outdated. We should investigate if we can upgrade them without breaking anything.

- Foundation (currently 6.2.2, 6.4.3 is available)
- JQuery (currently 2.2.2, 3.2.1 is the latest release)
- Font Awesome (currently 4.5.0, 4.7.0 is available)

**Comment by raju249** [comment]
@canihavesomecoffee 
Can you please assign me this?
Seems small issue, will help me to get acquainted with codebase.

Thanks

**Comment by saurabhshri** [comment]
@raju249 just start working, if you'd like to work. No need to be assigned :-)

**Comment by raju249** [comment]
Yes @saurabhshri :-)☺️

**Comment by raju249** [comment]
If I am not mistaken, the files that we need to change are in 
```static/js/vendor/``` and ``` static/css```.

Let me know if this is incorrect or also some more files are to be updated.
Thanka

**Comment by satyammittal** [comment]
I guess All the tasks are completed.
This needs to be closed.
