### ISSUE TITLE
[PROPOSAL] Generate Build Status Badges for all build scripts and methods.

### ISSUE THREAD

**Issue by saurabhshri** [CCExtractor/sample-platform#111]
**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/sample-platform/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/sample-platform/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never visited/used the platform.
- [ ] I have used the platform just a couple of times.
- [ ] I have used the platform extensively, but have not contributed previously.
- [x] I am an active contributor to the platform.

---

Enable sample platform to generate a pass/fail image (preferably SVG) based on the recent commit's test result so that it can be included as image (as badge) in CCExtractor Readme file.

Brief workflow :
- Sample Platform runs test on a commit.
- Based on the result, certain images (Build:Success / Build:Fail) are generated at a fixed location (say sampleplatform.ccextractor.org/buildtest/results/linux-cmake.svg OR sampleplatform.ccextractor.org/buildtest/results/linux-build.svg et cetera).

It needs to generate images for all build scripts which are tested on Sample Platform.

**Comment by saurabhshri** [comment]
An idea for probable implementation (may or may not be used) :  

1. We place the relevant SVGs in static directory (`success.svg`, `failure.svg`, `unknown.svg`).

2. As soon as the test for commit completes, the SVG based on result is copied (overwrite if already exists) from the above directory to the directory which will serve the image, say `sampleplatform.ccextractor.org/buildtest/results/` and rename it to `{platform}-{testscript}.svg`.

3. With this, the image will permanently be hosted on a fixed URL, say `sampleplatform.ccextractor.org/buildtest/results/linux-build.svg` which we can easily include in our readme.

With this, the images will be changed only once commit is made, and we'll also not need any external dependency.

**Comment by canihavesomecoffee** [comment]
Closing as badges for Windows / Linux should be available. Travis is handling Linux/Mac different build scripts.
