### ISSUE TITLE
[BUG] Recursion error when one side is empty

### ISSUE THREAD

**Issue by canihavesomecoffee** [CCExtractor/sample-platform#146]
Sample platform commit (found at the bottom of each page) : **Any**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/sample-platform/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/sample-platform/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never visited/used the platform.
- [ ] I have used the platform just a couple of times.
- [ ] I have used the platform extensively, but have not contributed previously.
- [x] I am the benevolent dictator of this platform.

---

The comparison script that generates the html diffs between versions cannot handle it when one side is empty and throws a recursion error. A check for this should be added.

**Comment by tejaram15** [comment]
Hello @canihavesomecoffee i am new to CCExtractor and i want to work on this issue. If you can please elaborate the issue or include the log files of error. i.e (The function or class) that generates the error, it would be helpful.

**Comment by saurabhshri** [comment]
@tejaram15 The diff generator crashes when one of the files is empty. The easiest way to reproduce this is extract the diff generator in a separate python script and pass two files one of which is empty.

**Comment by canihavesomecoffee** [comment]
1 point for @prabhakarpd7284 in case we are selected for GSoC 🥇
