### ISSUE TITLE
[BUG] Foundation upgrade broke lay-out

### ISSUE THREAD

**Issue by canihavesomecoffee** [CCExtractor/sample-platform#165]
**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/sample-platform/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/sample-platform/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never visited/used the platform.
- [ ] I have used the platform just a couple of times.
- [ ] I have used the platform extensively, but have not contributed previously.
- [x] I am an the benevolent dictator of this repository.

---

For GCi, we upgraded Foundation from v 6.2.2 to v 6.4.3 (see https://github.com/CCExtractor/sample-platform/commit/e7c5185f84c721aa57eb94abe476b2cdf283b7b0), but that broke quite some lay-outs. That either needs to be fixed by changing the grid layout we're using, or maybe by totally replacing Foundation with another library.

**Comment by MatejMecka** [comment]
Sorry @canihavesomecoffee

**Comment by sanchaymittal** [comment]
Mind if i work on this issue?

**Comment by MatejMecka** [comment]
Sure

**Comment by sanchaymittal** [comment]
It would be great if you could, you help me with proceeds to the problem to achieve target efficiency

**Comment by sanchaymittal** [comment]
![screenshot from 2018-02-17 02-30-18](https://user-images.githubusercontent.com/31698676/36329106-cea9690a-138a-11e8-9c2e-126cedb5dbd8.png)

**Comment by sanchaymittal** [comment]
Will this make the things right?

**Comment by satyammittal** [comment]
Check mobile responsive also

**Comment by satyammittal** [comment]
Though i prefer the footer to be just after the whole text, not at the bottom of the page. Little indentation is wrong, as far i can see

**Comment by sanchaymittal** [comment]
I checked the mobile responsive also.

**Comment by sanchaymittal** [comment]
Please check #188

**Comment by saurabhshri** [comment]
Looks like #189 and #188 are for the same issue. In future, please update the original PR with your changes. For now, please close the stale PR.

**Comment by sanchaymittal** [comment]
Ok i will keep that in my mind but for the record i closed that PR 15 hours ago.

**Comment by saurabhshri** [comment]
@sanchaymittal my bad then :) I am sorry!

**Comment by sanchaymittal** [comment]
@saurabhshri Np  :bowtie:

**Comment by MatejMecka** [comment]
#189 was merged? Should this be closed?

**Comment by canihavesomecoffee** [comment]
As long as I'm not sure there's nothing left to fix, no.
