### ISSUE TITLE
Python documentation

### ISSUE THREAD

**Issue by canihavesomecoffee** [CCExtractor/sample-platform#21]
The code of the sample platform has some documentation, but it lacks more of the so-called doc-blocks. Your task is to add them for a couple of files (minimum 3)

Steps:
- Clone/download the GitHub repository
- Edit the python files to add documentation (keep PEP-8 compliancy in mind)
- Make a pull request with the changes

**Comment by canihavesomecoffee** [comment]
Worth 1 point for GSoC Quali.

**Comment by pranavsid98** [comment]
Hi. I'd like to work on this. Thanks

**Comment by thealphadollar** [comment]
fixed with commits for #282
