### ISSUE TITLE
Handle merge/rebase conflict

### ISSUE THREAD

**Issue by canihavesomecoffee** [CCExtractor/sample-platform#22]
The sample platform automatically updates an existing repository with the newest commits from the master version of CCExtractor. However, sometimes this gives merge conflicts. Investigate the existing code and find a solution so that this doesn't halt the platform anymore.

The rebase is currently removed (see eade2d516f4598ad6724b412408af7f871db4f51), but it should be coming back at some point.

**Comment by TheClashster** [comment]
Another one down 🎉
