### ISSUE TITLE
[BUG] Make test progress page responsive

### ISSUE THREAD

**Issue by satyammittal** [CCExtractor/sample-platform#225]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Sample platform commit (found at the bottom of each page) : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/sample-platform/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/sample-platform/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never visited/used the platform.
- [ ] I have used the platform just a couple of times.
- [ ] I have used the platform extensively, but have not contributed previously.
- [x] I am an active contributor to the platform.

---

![pic1](https://user-images.githubusercontent.com/15922592/45705826-2e3d6a00-bb98-11e8-988b-8c5d327ab7b5.png)
![pic2](https://user-images.githubusercontent.com/15922592/45705828-2ed60080-bb98-11e8-930f-8c52d971010d.png)
[Test Progress page](https://sampleplatform.ccextractor.org/test/1723) is not responsive. We can see this issue in 400 x 500 display.
Either create a new design which is better and responsive or make this design responsive.

**Comment by parammittal16** [comment]
@satyammittal Can i work on this ?

**Comment by satyammittal** [comment]
@parammittal16 Yes

**Comment by negative0** [comment]
@sanchaymittal, I see that the issue is still open. Shall I work on this?

**Comment by canihavesomecoffee** [comment]
@negative0 Yes, if an issue is open you can just start working on it without asking for permission.
