### ISSUE TITLE
[PROPOSAL] Send Issue Link And User In Issue Mail

### ISSUE THREAD

**Issue by thealphadollar** [CCExtractor/sample-platform#231]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Sample platform commit (found at the bottom of each page) : **6c130cef21**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/sample-platform/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/sample-platform/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never visited/used the platform.
- [X] I have used the platform just a couple of times.
- [ ] I have used the platform extensively, but have not contributed previously.
- [ ] I am an active contributor to the platform.

---
Currently, the mail sent for new issues of the CCExtractor repo has the following formatting (and content).

![screenshot from 2018-10-23 00-49-37](https://user-images.githubusercontent.com/32812320/47314152-7a2f7300-d65e-11e8-98ef-b46d4a99bd92.png)

It would be a lot more convenient to view them if **a link to the issue was added** along with the link to the issue opener's github profile (name is already displayed but requires change in formatting to be more prominent).

**Comment by canihavesomecoffee** [comment]
Relevant code:

https://github.com/CCExtractor/sample-platform/blob/master/mod_ci/controllers.py#L502

**Comment by MatejMecka** [comment]
#232 implements this
