### ISSUE TITLE
[Proposal] Add function to fetch latest ccextractor version from github

### ISSUE THREAD

**Issue by anshul1912** [CCExtractor/sample-platform#255]
Sample platform commit (found at the bottom of each page) : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [ ] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/sample-platform/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/sample-platform/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never visited/used the platform.
- [X] I have used the platform just a couple of times.
- [ ] I have used the platform extensively, but have not contributed previously.
- [ ] I am an active contributor to the platform.

---

Instead of fetching ccextractor version from database, write a python function to fetch version information.

**Comment by canihavesomecoffee** [comment]
You can't directly fetch it, as that's introducing a dependency on GH. What can be done though, is locking on the webhook for releases, and auto-add it to our database (and reset all the necessary stuff).

**Comment by canihavesomecoffee** [comment]
See https://github.com/CCExtractor/sample-platform/blob/master/mod_ci/controllers.py#L649

**Comment by satyammittal** [comment]
look like there is some bug in webhook code. I am looking into it.
