### ISSUE TITLE
[PROPOSAL] Improve Latest CCEx Version Representation

### ISSUE THREAD

**Issue by thealphadollar** [CCExtractor/sample-platform#267]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Sample platform commit (found at the bottom of each page) : **32d7af6a46**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/sample-platform/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/sample-platform/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never visited/used the platform.
- [ ] I have used the platform just a couple of times.
- [ ] I have used the platform extensively, but have not contributed previously.
- [X] I am an active contributor to the platform.

---

### The Issue

We currently redirect users to sourceforge links, which we are not maintaining anymore.

### The Fix

We are using github releases to maintain binaries and information regarding new releases and we can use the same in order to automatically update the page.

References:
- https://github.com/CCExtractor/ccextractor/releases

cc/ @satyammittal Please add more details.

**Comment by satyammittal** [comment]
We are updating the release information when webhook is triggered. Webhook details are available at:https://developer.github.com/webhooks/.
Code for release update is at: https://github.com/CCExtractor/sample-platform/blob/master/mod_ci/controllers.py#L705.

Need to find and fix the issue why it is still not updating.

**Comment by thealphadollar** [comment]
@canihavesomecoffee Can i get access to the logs of the sample-platform from around the time when @cfsmp3 made the release so that I can see the details?

**Comment by canihavesomecoffee** [comment]
Release was made 21st, at 20:52 CEST.

Logs around that time:
```
[2019-05-21 20:41:10 +0200] [26786] [DEBUG] POST /start-ci
[2019-05-21 20:41:40 +0200] [26786] [DEBUG] Ignoring EPIPE
[INFO] [<windows>] Reverted to Updated machine for win2k8
[WARNING] [<windows>] Could not delete rebase-apply
libvirt: QEMU Driver error : Requested operation is not valid: domain is already running
[CRITICAL] [<windows>] Failed to launch VM win2k8
[2019-05-21 20:52:03 +0200] [53097] [DEBUG] POST /start-ci
[2019-05-21 20:52:34 +0200] [25453] [CRITICAL] WORKER TIMEOUT (pid:53097)
[2019-05-21 20:52:34 +0200] [53097] [INFO] Worker exiting (pid: 53097)
[2019-05-21 20:52:35 +0200] [30559] [INFO] Booting worker with pid: 30559
[2019-05-21 20:53:53 +0200] [30559] [DEBUG] POST /progress-reporter/2105/xxx
[2019-05-21 20:53:56 +0200] [26786] [DEBUG] POST /progress-reporter/2105/xxx
```

Nothing there. Not suprisable, that section of the code doesn't log anything...

**Comment by thealphadollar** [comment]
We had not configured the webhook to send release events. It's fixed now.
