### ISSUE TITLE
[PROPOSAL] Dark Theme

### ISSUE THREAD

**Issue by MatejMecka** [CCExtractor/sample-platform#273]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Sample platform commit (found at the bottom of each page) : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/sample-platform/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/sample-platform/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never visited/used the platform.
- [ ] I have used the platform just a couple of times.
- [ ] I have used the platform extensively, but have not contributed previously.
- [X] I am an active contributor to the platform.

---

Currently the Sample Platform offers a white theme and my eyes hurt :D 

Dark theme is on the rise and `prefers-color-scheme` is starting to get implemented in other browsers and not so many people will be happy to find out they will be stuck with a white theme :D 

So my Proposal is to create a Dark Theme for others so it's pleasing to their eyes and it helps save battery.

**Comment by thealphadollar** [comment]
Here are some links that might be good references when we start adding this.

- https://dribbble.com/shots/2978433-Dark-Foundation
- https://dribbble.com/outlane/projects/427603-ZURB-Foundation-Themes

Also, I would try to implement a toggle for the two modes.

**Comment by Tarun-Arora** [comment]
Sir, I would like to work on this proposal to implement a dark theme too for this project, please let me know if it is available.

**Comment by thealphadollar** [comment]
Hey Tarun, please feel free to make any changes related to this issue. Also, let us know if you need any help.

**Comment by canihavesomecoffee** [comment]
Closed by #613
