### ISSUE TITLE
[PROPOSAL] Improve Comparison Algorithm

### ISSUE THREAD

**Issue by thealphadollar** [CCExtractor/sample-platform#288]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Sample platform commit (found at the bottom of each page) : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ ] I have checked that the issue I'm posting isn't already reported.
- [ ] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/sample-platform/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/sample-platform/issues)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never visited/used the platform.
- [ ] I have used the platform just a couple of times.
- [ ] I have used the platform extensively, but have not contributed previously.
- [x] I am an active contributor to the platform.

---

The comparison of expected output and the output got from the test is tightly
hard-coded as it is done by simply matching the file hashes. This causes a lot of issues, a few of which are mentioned below.
- Intolerance to a slight change in the timestamp.
- Intolerance to detection of “,” as “.” or vice versa due to update in OCR.
- Intolerance to a slight error in whitespace matching

A more flexible approach can be used; we will not mark a test as a [failure if the results value returned is not None](https://github.com/CCExtractor/sample-platform/blob/dbd11465f8d31eed10071c2df39dfd6a0f5dfa83/mod_ci/controllers.py#L865). Instead, if the results are not None, a separate function will take in the result lines of the files and do a diff again once.

I went through a couple of failed tests and I could gather that the following toleration options could be provided while setting the tests (and a global config for CI). All these operations can be done using the replace method on strings.

- Whitespace: Whitespace differences should be ignored.
- List of similar characters: Characters which are similar and can be ignored such
as “.” and “,” or “!” and “1” can be made.
- Slight delay in time: If the time variance is varying by only a slight, the file can be
marked as safe. For this, we will parse all the integers from the different lines and
compare them and see if the difference is less than specified by the user.

cc/ @canihavesomecoffee @satyammittal Please provide your inputs on the same.

**Comment by thealphadollar** [comment]
@canihavesomecoffee Should we be giving users (test-runners) the option to have strict checking enabled?

I think it will be much better if we have it enabled for all?

Maybe just admins should be able to interact with it?

What do you suggest?

**Comment by thealphadollar** [comment]
@canihavesomecoffee I'm starting to work on this for the moment.

**Comment by thealphadollar** [comment]
@canihavesomecoffee @satyammittal I need guidance on this issue. I'm unable to find where I should be making changes. It seems like we do it inside the VM and just output the result whether the file hashes match or not. And for that too we use a script `ccextractortester` which is not present in the codebase.

If this cannot be done, we should fix this by completing #290

**Comment by aadibajpai** [comment]
wontfix generally implies that the bug will never be fixed (not even in the future). I don't think that's the case here.

**Comment by thealphadollar** [comment]
Thanks @aadibajpai

**Comment by canihavesomecoffee** [comment]
Closing as this idea is no longer valid; We should store multiple "correct" versions instead and compare against those.
