### ISSUE TITLE
[IMPROVEMENT] Update Outdated Expected Output Files

### ISSUE THREAD

**Issue by thealphadollar** [CCExtractor/sample-platform#290]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Sample platform commit (found at the bottom of each page) : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [ ] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ ] I have checked that the issue I'm posting isn't already reported.
- [ ] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/sample-platform/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/sample-platform/issues)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never visited/used the platform.
- [ ] I have used the platform just a couple of times.
- [ ] I have used the platform extensively, but have not contributed previously.
- [ ] I am an active contributor to the platform.

---

A few of the files (expected outputs) on the server are incorrect due to which regression tests fail. These include new features such as display of colors etc.

We should update them.

**Comment by thealphadollar** [comment]
@canihavesomecoffee Can you please guide me on this?

**Comment by canihavesomecoffee** [comment]
You'll just have to re-run the samples with the newest version and provide me with the files so I can update them :p

**Comment by thealphadollar** [comment]
Can you please give me the samples? Or a link to download or some way from where I can get them on the sample-platform test server and then run them with CCExtractor.

**Comment by canihavesomecoffee** [comment]
They are available on the sample platform itself :)

Alternatively (and might be better), is that you write a python script to do it automatically on the platform server :)

**Comment by thealphadollar** [comment]
Comment from @canihavesomecoffee about resources:

> See the config
> Or the download feature
> You can find needed vars there

**Comment by thealphadollar** [comment]
Working on this now; I'm creating a python script that will run with an installation of CCExtractor and output new samples.

**Comment by thealphadollar** [comment]
Closed via #321
