### ISSUE TITLE
[PROPOSAL] Revamp Sample-Platform Design

### ISSUE THREAD

**Issue by thealphadollar** [CCExtractor/sample-platform#292]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Sample platform commit (found at the bottom of each page) : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [ ] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ ] I have checked that the issue I'm posting isn't already reported.
- [ ] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/sample-platform/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/sample-platform/issues)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never visited/used the platform.
- [ ] I have used the platform just a couple of times.
- [ ] I have used the platform extensively, but have not contributed previously.
- [ ] I am an active contributor to the platform.

---

We use Foundation 6.4 and the latest version, as of 5 April, is 6.5. There are no major changes in the framework as such but porting to the new version is always better. So, at first, I’ll update our framework to version 6.5.

Post the update, I'll try to bring in the following changes:

- Make the title bar consistent over all screen sizes: currently, it’s just shown on
small screen sizes and not large ones.
- Improve menu style: a vertical style menu is good for smaller screens but doesn’t
look good on large screens and hence I’ll be implementing a horizontal style.
-  Improve typography on each page: Currently, there is no appropriate emphasis on the title and all the text tends to blend with each other. There is no proper
alignment of the elements as well. I’ll address these issues for all the pages of
the sample platform.
- Fix #273 

cc/ @canihavesomecoffee @satyammittal @MatejMecka @aadibajpai @T1duS Please provide your inputs on this.

References:
- https://vtldesign.com/brand-development/graphic-design/importance-typography-part-1-fonts-speak-louder-words/

**Comment by aadibajpai** [comment]
While I agree that the platform could do with a few upgrades aesthetically speaking, a lot of design varies from person to person. For example I find the vertical menu better than a horizontal nav bar. 

You could probably come up with a mockup first that can be deliberated upon before the implementation. For example, adding a dark mode is cool but what primary color will you use for the dark (Rich Black, Charcoal, #000000) or what accent color will you use. 

I think that would be a nice way to go about this :D

**Comment by MatejMecka** [comment]
We can also work on displaying an accurate representation of the Open Graph Protocol cards such as they display much more information rather than show only the icon and description
