### ISSUE TITLE
[PROPOSAL] Improved Installer

### ISSUE THREAD

**Issue by thealphadollar** [CCExtractor/sample-platform#293]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Sample platform commit (found at the bottom of each page) : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [ ] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ ] I have checked that the issue I'm posting isn't already reported.
- [ ] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/sample-platform/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/sample-platform/issues)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never visited/used the platform.
- [ ] I have used the platform just a couple of times.
- [ ] I have used the platform extensively, but have not contributed previously.
- [ ] I am an active contributor to the platform.

---

Currently, the sample-platform has a shell script to help in installation on Linux platforms and the same script is used for windows installation after setting up native Linux app runner Cygwin on Windows.

Below are the proposed improvements for the same (more to be added later):

- if MySQL client is not found, installation is run for the same but irrespective of the outcome of the installation process, the script moves forward.
-  not displaying the passwords

References:
- https://stackoverflow.com/questions/4316730/linux-scripting-hiding-user-input-on-terminal

NOTE: This is to be done at last.

cc/ @MatejMecka @satyammittal @aadibajpai @T1duS  Please provide your insights of installing the same and suggesting areas to ease pain.

**Comment by MatejMecka** [comment]
> if MySQL client is not found, installation is run for the same but irrespective of the outcome of the installation process, the script moves forward.

Maybe we can inform the User about this and offer the user the option to quit the installation, try again, install a replacement dependency?

**Comment by thealphadollar** [comment]
Update the method of setting up data in the database which currently breaks if a data is already present.
