### ISSUE TITLE
[IMPROVEMENT] Improve Docstring In Tests

### ISSUE THREAD

**Issue by thealphadollar** [CCExtractor/sample-platform#304]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Sample platform commit (found at the bottom of each page) : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/sample-platform/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/sample-platform/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never visited/used the platform.
- [ ] I have used the platform just a couple of times.
- [ ] I have used the platform extensively, but have not contributed previously.
- [x] I am an active contributor to the platform.

---

We've `pydocstyle` setup on the modules and we currently exclude 'tests' from the documentation check.

We should aim to achieve no errors in docstrings using `pydocstyle` for tests as well.

Most of the docstrings have been done keeping in mind the purpose of writing thorough tests; they purposedly lack (unlike the modules) "excellent" docstrings to save time.

**Comment by pieceofeden** [comment]
I would like to take this up.

**Comment by canihavesomecoffee** [comment]
There's no need to request, just start working on it and open some PR's.

**Comment by lkbhitesh07** [comment]
Hello @canihavesomecoffee, can you please tell me which files to add docstring, or is it I have to add to all files in `tests` folder, actually I'm a bit new to this environment that's why.
Thankyou.

**Comment by canihavesomecoffee** [comment]
As the description mentions, all files in the tests folder are skipped because some lack docstrings... So if we want to re-enable the check, everywhere in the tests folder where a docstring is missing needs one added.

**Comment by dukkee** [comment]
Hey @thealphadollar, I started to work on this issue and decreased from ~380 errors to ~130 ones for now. I have a question regarding modules docstrings. In my opinion, no need to do it for every module, because we will have enough descriptions in functions and classes. We can skip it by adding of the `add-ignore=D100` to the pydocstylerc config.

**Comment by thealphadollar** [comment]
Yes. I think that'll be better as modules are pretty nicely organized in
our case, to begin with.

Can you please raise a PR with the fixes? I'm glad you could fix the errors.

**Comment by dukkee** [comment]
@thealphadollar I didn't finish yet, but yes, sure, I will add in 5-10 mins a draft PR. I want to connect to your project as a part of GSoC, so your and Willem help will be really great, thank you
