### ISSUE TITLE
[PROPOSAL] Provide Message If User Not Found

### ISSUE THREAD

**Issue by thealphadollar** [CCExtractor/sample-platform#315]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Sample platform commit (found at the bottom of each page) : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [ ] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ ] I have checked that the issue I'm posting isn't already reported.
- [ ] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/sample-platform/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/sample-platform/issues)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never visited/used the platform.
- [ ] I have used the platform just a couple of times.
- [ ] I have used the platform extensively, but have not contributed previously.
- [ ] I am an active contributor to the platform.

---

Provide a message if user if not found instead of a generic message.

![Screenshot from 2019-07-05 23-53-20](https://user-images.githubusercontent.com/32812320/60739607-3bd5ac00-9f80-11e9-8b73-b3db4c7abbce.png)

**Comment by canihavesomecoffee** [comment]
Not a valid issue; for security reasons you should never acknowledge that the account is linked to an email address (otherwise it can be used for harvesting valid email addresses)
