### ISSUE TITLE
[PROPOSAL] Create a Docker Image of the Sample Platform

### ISSUE THREAD

**Issue by MatejMecka** [CCExtractor/sample-platform#333]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Sample platform commit (found at the bottom of each page) : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/sample-platform/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/sample-platform/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never visited/used the platform.
- [ ] I have used the platform just a couple of times.
- [ ] I have used the platform extensively, but have not contributed previously.
- [X] I am an active contributor to the platform.

---

Currently if someone wants to develop or run the sample platform that person needs to compile it themselves by hand on the machine they choose. Dealing with dependencies errors too for different platforms might be a pain for some.

What if we created a Docker image so when someone wants to get started on the project all they do is run that docker image?

**Comment by aadibajpai** [comment]
@canihavesomecoffee hates Docker

**Comment by MatejMecka** [comment]
Any alternatives to Docker for example? Something we can build an image

**Comment by canihavesomecoffee** [comment]
Docker might work for the majority, but we have dependencies on kvm & such. I'm not sure if that is even possible to run kvm inside a Docker image ;)

**Comment by canihavesomecoffee** [comment]
And "compile by hand" is not really the correct description.... If you run the setup script, and follow the instructions, it should work pretty well already thanks to the improvements that were made this summer...

**Comment by thealphadollar** [comment]
@MatejMecka I feel that this would be an overkill, especially considering that we require virtual machines to run on the system.

A better solution would be to create an instance of the current system as a docker image. And save it for ourselves in case of backup or failure of the system.

**Comment by thealphadollar** [comment]
@MatejMecka Please reopen the issue if we need to work on this 💯
