### ISSUE TITLE
[PROPOSAL] Add remove button to the blocked users functionality

### ISSUE THREAD

**Issue by aadibajpai** [CCExtractor/sample-platform#335]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Sample platform commit (found at the bottom of each page) : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/sample-platform/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/sample-platform/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never visited/used the platform.
- [ ] I have used the platform just a couple of times.
- [ ] I have used the platform extensively, but have not contributed previously.
- [x] I am an active contributor to the platform.

---

Currently, it's a separate form where you input a GitHub ID. Instead, there should be an "x" button per every user blocked so that it is more user friendly to unblock someone.

**Comment by Devil-Echo** [comment]
can you elaborate this issue, i want to work on it

**Comment by canihavesomecoffee** [comment]
Currently the Sample Platform uses a separate form to unblock blocked users. If you have a list of blocked users, you need to copy/paste the ID of that user into the form below to remove the user from the list.

The idea/wanted result for this issue is to integrate a removal button in the table, so you can unblock users with a single click instead.

Related code:
https://github.com/CCExtractor/sample-platform/blob/master/mod_ci/controllers.py#L1252
https://github.com/CCExtractor/sample-platform/blob/master/templates/ci/blocked_users.html

**Comment by Devil-Echo** [comment]
I have some problems setting up the sample-platform in the configuration part, which asks to enter some info regarding these -

APPLICATION_ROOT = ${config_application_root}
CSRF_ENABLED = True
DATABASE_URI = '${config_db_uri}?charset=utf8'
GITHUB_TOKEN = '${github_token}'
GITHUB_OWNER = '${github_owner_name}'
GITHUB_REPOSITORY = '${github_repository}'
SERVER_NAME = '${server_name}'
EMAIL_DOMAIN = '${email_domain}'
EMAIL_API_KEY = '${email_api_key}'
HMAC_KEY = '${hmac_key}'
GITHUB_DEPLOY_KEY = '${github_deploy_key}'
GITHUB_CI_KEY = '${github_ci_key}'
INSTALL_FOLDER = '${root_dir}'
KVM_LINUX_NAME = '${kvm_linux_name}'
KVM_WINDOWS_NAME = '${kvm_windows_name}'
KVM_MAX_RUNTIME = $kvm_max_runtime # In minutes
SAMPLE_REPOSITORY = '${sample_repository}'
SESSION_COOKIE_PATH = '/'
FTP_PORT = $ftp_port
MAX_CONTENT_LENGTH = $max_content_length
MIN_PWD_LEN = $min_pwd_len
MAX_PWD_LEN = $max_pwd_len

Can u plz help?

**Comment by thealphadollar** [comment]
What exact issue are you facing?

Please elaborate.

**Comment by Devil-Echo** [comment]
@thealphadollar 
![Screenshot from 2020-01-09 19-47-08](https://user-images.githubusercontent.com/53405160/72076627-d346fd80-331b-11ea-8894-d8b93af0eb16.png)

**Comment by Devil-Echo** [comment]
what to assign to these fields?

**Comment by thealphadollar** [comment]
Well, answer what is the correct answer. For example, for the question "domain this will be running on?", give "127.0.0.1". And similar for others give it accordingly. You would not be requiring a lot of settings and you can leave them blank such as EMAIL API Key etc.

**Comment by lkbhitesh07** [comment]
Hello @canihavesomecoffee, I just ran through the complete code you have provided and found interesting to work on this issue, before that I want to experience this locally So will you please guide me how to do that. I'm trying to figure that out because only after that I'll get to know better where to add that particular button and how.
Thanks

**Comment by canihavesomecoffee** [comment]
The first step is checking the installation manual for the sample platform which is located here on the repo.

**Comment by lkbhitesh07** [comment]
@canihavesomecoffee I'm done with the installation.

**Comment by aadibajpai** [comment]
closed in #510
