### ISSUE TITLE
[BUG] The number of queued tests is always 0

### ISSUE THREAD

**Issue by NilsIrl** [CCExtractor/sample-platform#338]
Sample platform commit: d98bd902bcdd7b9a24893c22ee21acb9b2257198

The [test page](https://sampleplatform.ccextractor.org/test/2619) reports that there are no tests queued:

![image](https://user-images.githubusercontent.com/26231126/72669018-b8177480-3a24-11ea-98a1-cee94dbcc4db.png)

Even though another is queued as well:

![image](https://user-images.githubusercontent.com/26231126/72669023-cd8c9e80-3a24-11ea-851c-0311c6863834.png)

**Comment by canihavesomecoffee** [comment]
Feel free to try and go for a fix if you're up for it.

Shouldn't be too hard I think :)

**Comment by NilsIrl** [comment]
For someone who might be attempting this: https://github.com/CCExtractor/sample-platform/blob/7eb8bbcef4c0abebd33cf9b010940046e41073ab/mod_test/controllers.py#L61

is the function that calculates the number of tests queued before.

**Comment by NilsIrl** [comment]
Here it seems to be reporting the wrong number of tests:

![image](https://user-images.githubusercontent.com/26231126/72670045-ac31af80-3a30-11ea-99d3-4646bde8d121.png)

![image](https://user-images.githubusercontent.com/26231126/72670049-b6ec4480-3a30-11ea-9466-9254ce04364b.png)

![image](https://user-images.githubusercontent.com/26231126/72670054-c79cba80-3a30-11ea-91c7-98749fb7694d.png)

**Comment by lkbhitesh07** [comment]
@canihavesomecoffee Now the only possibility I can think of it to occur is when the length of `test.process` is not 0 because then only the variable `queued_tests` will remain 0 and pass on to the final returns.
Thanks
