### ISSUE TITLE
Following the installation instructions is not enough, to run the project. 

### ISSUE THREAD

**Issue by zelzhan** [CCExtractor/sample-platform#347]
Please prefix your issue with one of the following: [QUESTION].

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [ ] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/sample-platform/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/sample-platform/issues)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [X] I have never visited/used the platform.
- [ ] I have used the platform just a couple of times.
- [ ] I have used the platform extensively, but have not contributed previously.
- [ ] I am an active contributor to the platform.

---

I'm a new contributor to the Sample Platform. While following all the instructions, entering the necessary information in installation page, including the certificates (self-signed), the sample platform is not running. It shows very strange error, which is attached to screenshot.
![image](https://user-images.githubusercontent.com/27729152/75212547-78754280-57b1-11ea-8e6b-83eaca99ab92.png)
![image](https://user-images.githubusercontent.com/27729152/75212603-a490c380-57b1-11ea-9f71-fe7d053462e9.png)
Which installation step I'm missing?

**Comment by canihavesomecoffee** [comment]
That looks like you're missing the `python` keyword when doing the sudo command... run.py is python code :)

**Comment by canihavesomecoffee** [comment]
Also, you might want to invalidate the current GitHub token you entered there and create a new one. It's usually not a good idea to post that kind of tokens publicly.

**Comment by zelzhan** [comment]
Thank you, that was pretty silly
