### ISSUE TITLE
Inconsistency of dependencies during installation.

### ISSUE THREAD

**Issue by zelzhan** [CCExtractor/sample-platform#348]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Sample platform commit (found at the bottom of each page) : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/sample-platform/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/sample-platform/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [X] I have never visited/used the platform.
- [ ] I have used the platform just a couple of times.
- [ ] I have used the platform extensively, but have not contributed previously.
- [ ] I am an active contributor to the platform.

---

I'm quite new to this project, but while installing the project, I have encountered several issues:
1) The dependencies, installed out of the box was not worked. Specifically this was related to the werkzueg package: https://github.com/zalando/connexion/issues/1149
2) The issue with this GitPython, whifch is described here: https://github.com/gitpython-developers/GitPython/issues/983

Everything seemed to be installed correctly. But here is the problem: after executing the command ```sudo python3 manage.py runserver``` my server is running. But when I go to the specified path, it shows ```404 not found error```. What can cause the problem? I have reproduced this issue on different computers.

![image](https://user-images.githubusercontent.com/27729152/75885984-af9ec000-5e51-11ea-9b54-1a18a0b00a36.png)

![image](https://user-images.githubusercontent.com/27729152/75886009-c04f3600-5e51-11ea-8235-9d494eb7c0b6.png)

**Comment by canihavesomecoffee** [comment]
That 404 is usually linked to wrong domain or path settings.

**Comment by thealphadollar** [comment]
Hey @zelzhan Thanks for bringing this to our notice. Can you give us some more details about the issues you faced during installation?

Also, as @canihavesomecoffee said, the 404 is due to wrong path settings.

**Comment by zelzhan** [comment]
Hello, @thealphadollar.

After execution of the installation script, and running the python script, I have faced the following issue:
1) ```ImportError: cannot import name 'FileStorage' from 'werkzeug'```. After manually installing the ```werkzeug==0.16``` resolved the issue.
2) ```ModuleNotFoundError: No module named 'gitdb.utils.compat'```. Using ```gitdb2==3.0.1``` solved the issue as well. 
3) I think it will be useful to mention, that using Python3.7 is required for this project.

Regarding the domain and path settings, could you guide me, how should I proceed to solve the problem? I will appreciate any help with this.

**Comment by thealphadollar** [comment]
@canihavesomecoffee What do you think? Should we pin the versions?

**Comment by thealphadollar** [comment]
@zelzhan Kindly give me some time, I'm busy ATM. I'll get back to you in a few days. In the meanwhile, you can join our slack and get your doubts cleared there :smile:

**Comment by canihavesomecoffee** [comment]
> @canihavesomecoffee What do you think? Should we pin the versions?

We already pin all requirements in our `requirements.txt`. If one of those contains a mistake that now causes the issues above, we should perhaps consider upgrading the pinned versions to something that fixes it.

Nevertheless, if the new version of the platform is done this summer and doesn't derive from this one, we could wonder if effort should be spent to fix.

@zelzhan If you want to make a PR with a fix for the issues in it, feel free :)

**Comment by aadibajpai** [comment]
> > @canihavesomecoffee What do you think? Should we pin the versions?
> 
> We already pin all requirements in our `requirements.txt`. If one of those contains a mistake that now causes the issues above, we should perhaps consider upgrading the pinned versions to something that fixes it.
> 
> Nevertheless, if the new version of the platform is done this summer and doesn't derive from this one, we could wonder if effort should be spent to fix.
> 
> @zelzhan If you want to make a PR with a fix for the issues in it, feel free :)

configure dependabot on the repo

**Comment by thealphadollar** [comment]
@canihavesomecoffee Can we please configure dependabot on the repository?

I would encourage you to raise a PR with the specified versions pinned in the `Pipfile` and `requirements.txt`.

**Comment by thealphadollar** [comment]
Closing this issue since we have already pinned the exact version in `requirements.txt` and `test-requirements.txt`.
