### ISSUE TITLE
[PROPOSAL] Replacing Login with Signup and Signin

### ISSUE THREAD

**Issue by lkbhitesh07** [CCExtractor/sample-platform#505]
Sample platform commit (found at the bottom of each page) : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/sample-platform/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/sample-platform/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never visited/used the platform.
- [X] I have used the platform just a couple of times.
- [ ] I have used the platform extensively, but have not contributed previously.
- [ ] I am an active contributor to the platform.

---

Just want to propose a simple edit, whenever we visit the site we just only see `Login` button, wouldn't it be great if we will implement two buttons `Signup` and `Signin`? Do let me know if we can implement it.
Thanks

**Comment by canihavesomecoffee** [comment]
We wouldn't mind. Just make sure it's not showing up to logged in users ;)

**Comment by gaurav879** [comment]
@canihavesomecoffee 
I would like to work on this issue, but I am a beginner so it would be very helpful if someone could guide me in completing this.

**Comment by thealphadollar** [comment]
Hey Gaurav! Thanks for showing interest. Please let us know how we should help you.

A good way to start with this would be to run the sample platform, test the current login, and understand how it works. Then we can chalk out changes and issues we need to tackle.

**Comment by devmrfitz** [comment]
@canihavesomecoffee I have made a PR for this issue. Request you to review it
