### ISSUE TITLE
[Question] Facing issues while setting up the local environment.

### ISSUE THREAD

**Issue by lkbhitesh07** [CCExtractor/sample-platform#508]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Sample platform commit (found at the bottom of each page) : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/sample-platform/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/sample-platform/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never visited/used the platform.
- [X] I have used the platform just a couple of times.
- [ ] I have used the platform extensively, but have not contributed previously.
- [ ] I am an active contributor to the platform.

---

![Screenshot from 2021-03-07 16-28-52](https://user-images.githubusercontent.com/44300735/110237979-f2afd980-7f64-11eb-8dec-7e7b3fddb724.png)

I'm not sure about the error I'm getting after writing the admin password, please take a look. Also, one more question I want to ask is that I'm unable to find anywhere the process to start the development server to see changes. I mean yes it's a flask application and we can simply do `flask run.py` to run the application but when I tried to do that it showed me that `no flask application` which means that the `requirements.txt` file hasn't run and the development locally is not done.
Thanks in advance.

**Comment by kvshravan** [comment]
@lkbhitesh07 Please follow the installation guide, you don't need to run the `run.py` file to start the platform. The platform is installed as a service, so you start it using `sudo service platform start`

**Comment by canihavesomecoffee** [comment]
Also, those SyntaxError's are pointing towards an outdated Python version.

Your Python version must be at least 3.6.

**Comment by Tarun-Arora** [comment]
@lkbhitesh07 Even if you are running ```flask run``` to start the platform before that please activate the virtual environment by running ```pipenv shell```.
