### ISSUE TITLE
Extend compilation with CMake

### ISSUE THREAD

**Issue by canihavesomecoffee** [CCExtractor/sample-platform#55]
Currently the Linux builds are done with the build shell script only.

Extend this so it also builds and checks if the CMakefile is a success.

Worth 1 point for GSoC qualification

Expected: a PEP-8 compliant PR.

**Comment by pranavsid98** [comment]
Hi. I am interested to work on this, Thanks.

**Comment by canihavesomecoffee** [comment]
Just start working on it and submit a PR. This also goes for the other issue you want to work on.

**Comment by saurabhshri** [comment]
With https://github.com/CCExtractor/ccextractor/commit/735f4392ddb7bd11efafc480358f9fcb980a10b3 CCExtractor builds successfully with CMake. 

Once Windows support is re-established, maybe add a check / build using CMake on Windows.
