### ISSUE TITLE
Foundation upgrade issues

### ISSUE THREAD

**Issue by canihavesomecoffee** [CCExtractor/sample-platform#620]
@Tarun-Arora 

I see many issues with the recent merge of the dark theme... Please look at them or I'll have to revert the PR.

![2022-01-08_15-46](https://user-images.githubusercontent.com/7365586/148648540-2a84d25f-219d-415a-945b-585d29750738.png)
![2022-01-08_15-45](https://user-images.githubusercontent.com/7365586/148648541-b88aa0ad-4e79-478f-be10-6c9b830b3955.png)
![2022-01-08_15-44](https://user-images.githubusercontent.com/7365586/148648543-a7a542ed-d565-445e-afad-53c464e128b4.png)
![2022-01-08_15-43_1](https://user-images.githubusercontent.com/7365586/148648544-026d3e76-43e3-4211-b804-d95b872ae81e.png)
![2022-01-08_15-43](https://user-images.githubusercontent.com/7365586/148648546-87e33455-e1c6-4754-b7bf-3650d707e924.png)
![2022-01-08_15-42](https://user-images.githubusercontent.com/7365586/148648547-86c2968c-0d1c-497a-b6aa-f50513e4644d.png)

**Comment by canihavesomecoffee** [comment]
![2022-01-08_15-49](https://user-images.githubusercontent.com/7365586/148648662-5d36055e-c849-46d1-9f7f-714bf24c6bb9.png)
![2022-01-08_15-48](https://user-images.githubusercontent.com/7365586/148648663-e63ae193-b49c-49ab-bca2-5609980690fe.png)
![2022-01-08_15-47](https://user-images.githubusercontent.com/7365586/148648665-dc00ed88-f35b-4eb2-8a58-5229e56ca6a5.png)

**Comment by Tarun-Arora** [comment]
Sir, I will see these issues and will revert you soon.

**Comment by canihavesomecoffee** [comment]
Looks all fixed, except for the sidebar background color in light-mode.

**Comment by canihavesomecoffee** [comment]
Then it's all fixed again :)
