### ISSUE TITLE
Installation script is not generating Github_client_id and Github_client_secret in config.py file

### ISSUE THREAD

**Issue by rdas6313** [CCExtractor/sample-platform#719]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Sample platform commit (found at the bottom of each page) : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/sample-platform/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/sample-platform/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never visited/used the platform.
- [ ] I have used the platform just a couple of times.
- [x] I have used the platform extensively, but have not contributed previously.
- [ ] I am an active contributor to the platform.

---

Installation script is not producing Github_client_id and Github_client_secret fields inside config.py file (I had to add those fields manually). Beacuse of that Link to github option is not working as shown in [video](https://drive.google.com/file/d/1WM7sxd3fuIh-Ji2ki4fV3xpwa6givSk2/view?usp=sharing) and also unable to create custom tests. Need to update installtion script, so that it generates both of those fields.

**Comment by Tarun-Arora** [comment]
Thanks, @rdas6313, for pointing this out.

**Comment by rdas6313** [comment]
Like to work on this if it is ok for you.

**Comment by rdas6313** [comment]
@Tarun-Arora Another thing to mention here, although token verification is successful, it is showing **[Platform][ERROR][2022-10-11 11:42:34,241] Failed to validate GitHub token** . As you can see from the [code ](https://gist.github.com/rdas6313/58183fa665679ac8bdffeb09df73cfe7) that in line no 18, if validity becomes True, then it is going to print the error log. Don't you think it should not log that ?

**Comment by Tarun-Arora** [comment]
> @Tarun-Arora Another thing to mention here, although token verification is successful, it is showing **[Platform][ERROR][2022-10-11 11:42:34,241] Failed to validate GitHub token** . As you can see from the [code ](https://gist.github.com/rdas6313/58183fa665679ac8bdffeb09df73cfe7) that in line no 18, if validity becomes True, then it is going to print the error log. Don't you think it should not log that ?

Yeah it should be in validate False part...

**Comment by rdas6313** [comment]
Are you going to do it ?

> > @Tarun-Arora Another thing to mention here, although token verification is successful, it is showing **[Platform][ERROR][2022-10-11 11:42:34,241] Failed to validate GitHub token** . As you can see from the [code ](https://gist.github.com/rdas6313/58183fa665679ac8bdffeb09df73cfe7) that in line no 18, if validity becomes True, then it is going to print the error log. Don't you think it should not log that ?
> 
> Yeah it should be in validate False part...

Are you going to do it ?

**Comment by Tarun-Arora** [comment]
> > > @Tarun-Arora Another thing to mention here, although token verification is successful, it is showing **[Platform][ERROR][2022-10-11 11:42:34,241] Failed to validate GitHub token** . As you can see from the [code ](https://gist.github.com/rdas6313/58183fa665679ac8bdffeb09df73cfe7) that in line no 18, if validity becomes True, then it is going to print the error log. Don't you think it should not log that ?
> > 
> > 
> > Yeah it should be in validate False part...
> 
> Are you going to do it ?

Yes okay, thank you

**Comment by rdas6313** [comment]
> > > > @Tarun-Arora Another thing to mention here, although token verification is successful, it is showing **[Platform][ERROR][2022-10-11 11:42:34,241] Failed to validate GitHub token** . As you can see from the [code ](https://gist.github.com/rdas6313/58183fa665679ac8bdffeb09df73cfe7) that in line no 18, if validity becomes True, then it is going to print the error log. Don't you think it should not log that ?
> > > 
> > > 
> > > Yeah it should be in validate False part...
> > 
> > 
> > Are you going to do it ?
> 
> Yes okay, thank you

You are welcome.
