### ISSUE TITLE
[BUG] Domain is already running error while running cron.py

### ISSUE THREAD

**Issue by rdas6313** [CCExtractor/sample-platform#727]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Sample platform commit (found at the bottom of each page) : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/sample-platform/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/sample-platform/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never visited/used the platform.
- [ ] I have used the platform just a couple of times.
- [x] I have used the platform extensively, but have not contributed previously.
- [ ] I am an active contributor to the platform.

---

When running cron for kicking off the CI platform, i am having the below errors. 
`[Platform][CRITICAL][2022-10-20 20:14:22,244] [<linux>] Failed to launch VM ubuntu20.04`
`[Platform][CRITICAL][2022-10-20 20:14:22,244] Information about failure: code: 55, domain: 10, level: 2, message: Requested operation is not valid: domain is already running`

This error is occuring because of this line `vm.create()` in mod_ci/controllers.py file
since `vm.revertToSnapshot(snapshot)` starting the domain before `vm.create()` and as a result of this error, Kvm table is not inserting new value.
@Tarun-Arora @thealphadollar  @canihavesomecoffee  If you give permission, i would like to fix this one.

**Comment by canihavesomecoffee** [comment]
You can work on it, but seems a bit pointless to me, as we're moving everything to GCP in the coming weeks...

**Comment by rdas6313** [comment]
If everything is moving to GCP then there is no point of doing this. When are you going to merge gsoc-22 branch with master ? and when do we get the required documentation related to GCP setup ? Actually i am really want to contribute to this project.

**Comment by Tarun-Arora** [comment]
Hey @rdas6313, the GCP setup is merged now to the master branch.
@thealphadollar we can close this issue...

**Comment by thealphadollar** [comment]
Thanks Tarun.
